//https://crm.byrobot.cn/api/devDecision/decisionTree?sceneDefId=73094&sceneNodeId=529526&environment=dev
export default {
  "code": 200,
  "data": {
    "decisionNodeBO": {
      "decisionId": 7615842,
      "sceneDefId": 73094,
      "parentId": -1,
      "sceneNodeId": 529526,
      "name": "普通话术",
      "answerIds": [],
      "childrenAnswerIds": [
        "默认"
      ],
      "refererId": null,
      "knowledge": "喂，您好",
      "knowledgeOssUrl": null,
      "knowledgeOssFullUrl": null,
      "index": 1,
      "keyword": null,
      "decisionType": 0,
      "acceptBreak": 0,
      "afterBreakType": 1,
      "action": 2,
      "knowledgeBaseId": null,
      "path": "557.9780000000001 -247.76159999999996",
      "nodeType": 0,
      "intentionDef": "{\"客户意向等级\":\"C级(明确拒绝)\"}",
      "labelInfoIds": null,
      "labelInfoItem": [],
      "actionParam": null,
      "smsTemplateId": -1,
      "answerKeywordDef": "{\"肯定\":[\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\"],\"拒绝\":[\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\"]}",
      "useEavesdrop": 0,
      "eavesdropParam": "",
      "attachmentSendFlag": 0,
      "attachment": null,
      "ttsType": 2,
      "transferSeatGroupId": null,
      "transferAction": null,
      "transferTelephone": null,
      "transferTelephoneEditable": false,
      "ivrParam": null,
      "childrenList": [
        {
          "decisionId": 7615464,
          "sceneDefId": 73094,
          "parentId": 7615842,
          "sceneNodeId": 529526,
          "name": "普通话术",
          "answerIds": [
            "默认"
          ],
          "childrenAnswerIds": [
            "肯定",
            "否定",
            "默认",
            "特殊"
          ],
          "refererId": null,
          "knowledge": "我这边是百应平台，请问您是${客户名称}吗？",
          "knowledgeOssUrl": null,
          "knowledgeOssFullUrl": null,
          "index": 1,
          "keyword": "",
          "decisionType": 0,
          "acceptBreak": 1,
          "afterBreakType": 1,
          "action": 2,
          "knowledgeBaseId": null,
          "path": "557.9780000000001 -45.68159999999989",
          "nodeType": 0,
          "intentionDef": "{\"客户意向等级\":\"C级(明确拒绝)\"}",
          "labelInfoIds": null,
          "labelInfoItem": [],
          "actionParam": null,
          "smsTemplateId": -1,
          "answerKeywordDef": "{\"肯定\":[\"有需要\",\"说下\",\"讲下\",\"你讲\",\"行啊\",\"了解下\",\"说吧\",\"对的\",\"对啊\",\"确实是\",\"是的\",\"当然\",\"肯定\",\"能去\",\"能啊\",\"行行\",\"接触过\",\"了解过\",\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\",\"是\",\"^[^不]*是的\",\"怎么\",\"^[^在]*哪里\",\"(说|干|做)(啥|什么|嘛)\",\"你说\",\"我是\",\"是啊\",\"嗯对\",\"嗯是\",\"^[^不]*(是我本人|是本人)\"],\"拒绝\":[\"暂时\",\"目前\",\"用不着\",\"用不到\",\"不了\",\"(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见)\",\"打错\",\"没兴趣\",\"搞错\",\"不感兴趣\",\"没.*需要\",\"不需要\",\"不愿意\",\"不考虑\",\"已经.*(有|过)\",\"我说我没\",\"我说我不\",\"不做\",\"不缺钱\",\"我有钱\",\"不用\",\"不想\",\"算了\",\"没有\",\"再见\",\"挂了\",\"加过\",\"没时间\",\"不必\",\"没必要\",\"算了吧\",\"打错了\",\"暂时不\",\"打错电话\",\"没.*接触\",\"不了解\",\"不知道\",\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\",\"不是\",\"不是本人\",\"不是我\",\"(别人|人家).*办的\",\"没有欠钱\",\"不记得\",\"没用过\",\"没(借|欠)过\",\"(时间|时候).*(借欠)(过|的|得)\",\"没.*(借|欠|消费)过\",\"没有用过\",\"打错了\",\"我没借\",\"我没有借\",\"我不欠\",\"(不|没).*(认识|下过).*(软件|平台|A|a)\",\"不认识\",\"认不到\"],\"特殊\":[\"干嘛\",\"做啥\",\"干啥\",\"哪的\",\"哪块\",\"没听清\",\"再说一遍\",\"有事\",\"哪个\",\"你说撒\",\"没信号\",\"听.*清\",\"你.*谁\"]}",
          "useEavesdrop": 0,
          "eavesdropParam": "",
          "attachmentSendFlag": null,
          "attachment": null,
          "ttsType": 2,
          "transferSeatGroupId": null,
          "transferAction": null,
          "transferTelephone": null,
          "transferTelephoneEditable": false,
          "ivrParam": null,
          "childrenList": [
            {
              "decisionId": 7615465,
              "sceneDefId": 73094,
              "parentId": 7615464,
              "sceneNodeId": 529526,
              "name": "跳转话术",
              "answerIds": [
                "肯定"
              ],
              "childrenAnswerIds": [],
              "refererId": null,
              "knowledge": "",
              "knowledgeOssUrl": null,
              "knowledgeOssFullUrl": null,
              "index": null,
              "keyword": "有需要,说下,讲下,你讲,行啊,了解下,说吧,对的,对啊,确实是,是的,当然,肯定,能去,能啊,行行,接触过,了解过,^((?!没有需要).)*有需要,^[^没]*需求,^[^(不|没)]*兴趣,是,^[^不]*是的,怎么,^[^在]*哪里,(说|干|做)(啥|什么|嘛),你说,我是,是啊,嗯对,嗯是,^[^不]*(是我本人|是本人)",
              "decisionType": 0,
              "acceptBreak": 0,
              "afterBreakType": 0,
              "action": 3,
              "knowledgeBaseId": null,
              "path": "269.98900000000003 130.94365000000005",
              "nodeType": 1,
              "intentionDef": "{}",
              "labelInfoIds": null,
              "labelInfoItem": [],
              "actionParam": "{}",
              "smsTemplateId": null,
              "answerKeywordDef": null,
              "useEavesdrop": 0,
              "eavesdropParam": "",
              "attachmentSendFlag": null,
              "attachment": null,
              "ttsType": 2,
              "transferSeatGroupId": null,
              "transferAction": null,
              "transferTelephone": null,
              "transferTelephoneEditable": false,
              "ivrParam": null,
              "childrenList": []
            },
            {
              "decisionId": 7615466,
              "sceneDefId": 73094,
              "parentId": 7615464,
              "sceneNodeId": 529526,
              "name": "普通话术",
              "answerIds": [
                "默认",
                "特殊"
              ],
              "childrenAnswerIds": [
                "肯定",
                "拒绝",
                "否定",
                "默认"
              ],
              "refererId": null,
              "knowledge": "您好，是这样的，我这边是百应平台，请问您是${客户名称}吗？",
              "knowledgeOssUrl": null,
              "knowledgeOssFullUrl": null,
              "index": null,
              "keyword": "干嘛,做啥,干啥,哪的,哪块,没听清,再说一遍,有事,哪个,你说撒,没信号,听.*清,你.*谁",
              "decisionType": 0,
              "acceptBreak": 0,
              "afterBreakType": 1,
              "action": 2,
              "knowledgeBaseId": null,
              "path": "557.9780000000001 156.39840000000004",
              "nodeType": 0,
              "intentionDef": "{}",
              "labelInfoIds": null,
              "labelInfoItem": [],
              "actionParam": null,
              "smsTemplateId": -1,
              "answerKeywordDef": "{\"肯定\":[\"有需要\",\"说下\",\"讲下\",\"你讲\",\"行啊\",\"了解下\",\"说吧\",\"对的\",\"对啊\",\"确实是\",\"是的\",\"当然\",\"肯定\",\"能去\",\"能啊\",\"行行\",\"接触过\",\"了解过\",\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\",\"^[^不]*是的\",\"怎么\",\"^[^在]*哪里\",\"(说|干|做)(啥|什么|嘛)\",\"你说\",\"我是\",\"是啊\",\"嗯对\",\"嗯是\"],\"拒绝\":[\"暂时\",\"目前\",\"用不着\",\"用不到\",\"不了\",\"(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见)\",\"打错\",\"没兴趣\",\"搞错\",\"不感兴趣\",\"没.*需要\",\"不需要\",\"不愿意\",\"已经.*(有|过)\",\"我说我不\",\"不做\",\"不用\",\"不想\",\"算了\",\"没有\",\"再见\",\"挂了\",\"加过\",\"没时间\",\"不必\",\"没必要\",\"算了吧\",\"打错了\",\"暂时不\",\"打错电话\",\"没.*接触\",\"不了解\",\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\",\"不是\",\"不是本人\",\"不是我\",\"(别人|人家).*办的\",\"没有欠钱\",\"不记得\",\"没用过\",\"没(借|欠)过\",\"(时间|时候).*(借欠)(过|的|得)\",\"没.*(借|欠|消费)过\",\"没有用过\",\"打错了\",\"我没借\",\"我没有借\",\"我不欠\",\"(不|没).*(认识|下过).*(软件|平台|A|a)\",\"不认识\",\"认不到\"]}",
              "useEavesdrop": 0,
              "eavesdropParam": "",
              "attachmentSendFlag": null,
              "attachment": null,
              "ttsType": 2,
              "transferSeatGroupId": null,
              "transferAction": null,
              "transferTelephone": null,
              "transferTelephoneEditable": false,
              "ivrParam": null,
              "childrenList": [
                {
                  "decisionId": 7615467,
                  "sceneDefId": 73094,
                  "parentId": 7615466,
                  "sceneNodeId": 529526,
                  "name": "跳转话术",
                  "answerIds": [
                    "肯定",
                    "默认"
                  ],
                  "childrenAnswerIds": [],
                  "refererId": null,
                  "knowledge": "",
                  "knowledgeOssUrl": null,
                  "knowledgeOssFullUrl": null,
                  "index": null,
                  "keyword": "有需要,说下,讲下,你讲,行啊,了解下,说吧,对的,对啊,确实是,是的,当然,肯定,能去,能啊,行行,接触过,了解过,^((?!没有需要).)*有需要,^[^没]*需求,^[^(不|没)]*兴趣,^[^不]*是的,怎么,^[^在]*哪里,(说|干|做)(啥|什么|嘛),你说,我是,是啊,嗯对,嗯是",
                  "decisionType": 0,
                  "acceptBreak": 0,
                  "afterBreakType": 0,
                  "action": 3,
                  "knowledgeBaseId": null,
                  "path": "206.99450000000002 317.06864999999993",
                  "nodeType": 1,
                  "intentionDef": "{}",
                  "labelInfoIds": null,
                  "labelInfoItem": [],
                  "actionParam": "{}",
                  "smsTemplateId": null,
                  "answerKeywordDef": null,
                  "useEavesdrop": 0,
                  "eavesdropParam": "",
                  "attachmentSendFlag": null,
                  "attachment": null,
                  "ttsType": 2,
                  "transferSeatGroupId": null,
                  "transferAction": null,
                  "transferTelephone": null,
                  "transferTelephoneEditable": false,
                  "ivrParam": null,
                  "childrenList": []
                },
                {
                  "decisionId": 7615468,
                  "sceneDefId": 73094,
                  "parentId": 7615466,
                  "sceneNodeId": 529526,
                  "name": "跳转话术",
                  "answerIds": [
                    "拒绝",
                    "否定"
                  ],
                  "childrenAnswerIds": [],
                  "refererId": null,
                  "knowledge": "不好意思，打扰了，${客户名称}在我们百应平台的借款即将到期，请您尽快通知他还款，谢谢，这边先不打扰了，再见！",
                  "knowledgeOssUrl": null,
                  "knowledgeOssFullUrl": null,
                  "index": null,
                  "keyword": "暂时,目前,用不着,用不到,不了,(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见),打错,没兴趣,搞错,不感兴趣,没.*需要,不需要,不愿意,已经.*(有|过),我说我不,不做,不用,不想,算了,没有,再见,挂了,加过,没时间,不必,没必要,算了吧,打错了,暂时不,打错电话,没.*接触,不了解,没.*需求,没.*打算,没.*想法,(没|不).*需要,不.*感兴趣,没.*兴趣,(没|不).*考虑,不知道,^((?!听不清楚|说不清楚).)*不清楚,不是,不是本人,不是我,(别人|人家).*办的,没有欠钱,不记得,没用过,没(借|欠)过,(时间|时候).*(借欠)(过|的|得),没.*(借|欠|消费)过,没有用过,我没借,我没有借,我不欠,(不|没).*(认识|下过).*(软件|平台|A|a),不认识,认不到",
                  "decisionType": 0,
                  "acceptBreak": 0,
                  "afterBreakType": 0,
                  "action": 1,
                  "knowledgeBaseId": null,
                  "path": "448.98350000000005 353.5684",
                  "nodeType": 1,
                  "intentionDef": "{}",
                  "labelInfoIds": "[12091]",
                  "labelInfoItem": [
                    {
                      "name": "不是本人",
                      "id": 12091
                    }
                  ],
                  "actionParam": "{}",
                  "smsTemplateId": -1,
                  "answerKeywordDef": null,
                  "useEavesdrop": 0,
                  "eavesdropParam": "",
                  "attachmentSendFlag": null,
                  "attachment": null,
                  "ttsType": 2,
                  "transferSeatGroupId": null,
                  "transferAction": null,
                  "transferTelephone": null,
                  "transferTelephoneEditable": false,
                  "ivrParam": null,
                  "childrenList": []
                }
              ]
            },
            {
              "decisionId": 7617921,
              "sceneDefId": 73094,
              "parentId": 7615464,
              "sceneNodeId": 529526,
              "name": "普通话术",
              "answerIds": [
                "否定"
              ],
              "childrenAnswerIds": [
                "肯定",
                "拒绝",
                "否定",
                "默认"
              ],
              "refererId": null,
              "knowledge": "不好意思，我这边需要再次确认一下您是不是${客户名称}?",
              "knowledgeOssUrl": null,
              "knowledgeOssFullUrl": null,
              "index": null,
              "keyword": "不知道,^((?!听不清楚|说不清楚).)*不清楚,不了解,不是,不是本人,不是我,(别人|人家).*办的,没有欠钱,不记得,没用过,没(借|欠)过,(时间|时候).*(借欠)(过|的|得),没.*(借|欠|消费)过,没有用过,打错了,我没借,我没有借,我不欠,(不|没).*(认识|下过).*(软件|平台|A|a),不认识,认不到",
              "decisionType": 0,
              "acceptBreak": 0,
              "afterBreakType": 1,
              "action": 2,
              "knowledgeBaseId": null,
              "path": "845.9670000000001 156.39840000000004",
              "nodeType": 0,
              "intentionDef": "{\"客户意向等级\":\"C级(明确拒绝)\"}",
              "labelInfoIds": null,
              "labelInfoItem": [],
              "actionParam": null,
              "smsTemplateId": -1,
              "answerKeywordDef": "{\"肯定\":[\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\",\"^[^不]*是的\",\"怎么\",\"^[^在]*哪里\",\"(说|干|做)(啥|什么|嘛)\",\"你说\",\"我是\",\"是啊\",\"嗯对\",\"嗯是\"],\"拒绝\":[\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\",\"暂时\",\"目前\",\"用不着\",\"用不到\",\"不了\",\"(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见)\",\"打错\",\"没兴趣\",\"搞错\",\"不感兴趣\",\"没.*需要\",\"不需要\",\"不愿意\",\"已经.*(有|过)\",\"我说我不\",\"不做\",\"不用\",\"不想\",\"算了\",\"没有\",\"再见\",\"挂了\",\"加过\",\"没时间\",\"不必\",\"没必要\",\"算了吧\",\"打错了\",\"暂时不\",\"打错电话\",\"没.*接触\",\"不了解\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\",\"不是\",\"不是本人\",\"不是我\",\"(别人|人家).*办的\",\"没有欠钱\",\"不记得\",\"没用过\",\"没(借|欠)过\",\"(时间|时候).*(借欠)(过|的|得)\",\"没.*(借|欠|消费)过\",\"没有用过\",\"打错了\",\"我没借\",\"我没有借\",\"我不欠\",\"(不|没).*(认识|下过).*(软件|平台|A|a)\",\"不认识\",\"认不到\"]}",
              "useEavesdrop": 0,
              "eavesdropParam": "",
              "attachmentSendFlag": 0,
              "attachment": null,
              "ttsType": 2,
              "transferSeatGroupId": null,
              "transferAction": null,
              "transferTelephone": null,
              "transferTelephoneEditable": false,
              "ivrParam": null,
              "childrenList": [
                {
                  "decisionId": 7617922,
                  "sceneDefId": 73094,
                  "parentId": 7617921,
                  "sceneNodeId": 529526,
                  "name": "跳转话术",
                  "answerIds": [
                    "肯定",
                    "默认"
                  ],
                  "childrenAnswerIds": [],
                  "refererId": null,
                  "knowledge": "",
                  "knowledgeOssUrl": null,
                  "knowledgeOssFullUrl": null,
                  "index": null,
                  "keyword": "^((?!没有需要).)*有需要,^[^没]*需求,^[^(不|没)]*兴趣,^[^不]*是的,怎么,^[^在]*哪里,(说|干|做)(啥|什么|嘛),你说,我是,是啊,嗯对,嗯是",
                  "decisionType": 0,
                  "acceptBreak": 0,
                  "afterBreakType": 0,
                  "action": 3,
                  "knowledgeBaseId": null,
                  "path": "701.9725000000001 345.06864999999993",
                  "nodeType": 1,
                  "intentionDef": "{}",
                  "labelInfoIds": null,
                  "labelInfoItem": [],
                  "actionParam": "{}",
                  "smsTemplateId": -1,
                  "answerKeywordDef": null,
                  "useEavesdrop": 0,
                  "eavesdropParam": "",
                  "attachmentSendFlag": 0,
                  "attachment": null,
                  "ttsType": 2,
                  "transferSeatGroupId": null,
                  "transferAction": null,
                  "transferTelephone": null,
                  "transferTelephoneEditable": false,
                  "ivrParam": null,
                  "childrenList": []
                },
                {
                  "decisionId": 7617923,
                  "sceneDefId": 73094,
                  "parentId": 7617921,
                  "sceneNodeId": 529526,
                  "name": "跳转话术",
                  "answerIds": [
                    "拒绝",
                    "否定"
                  ],
                  "childrenAnswerIds": [],
                  "refererId": null,
                  "knowledge": "不好意思，打扰了，${客户名称}在我们百应平台的借款即将到期，请您尽快通知他还款，谢谢，这边先不打扰了，再见！",
                  "knowledgeOssUrl": null,
                  "knowledgeOssFullUrl": null,
                  "index": null,
                  "keyword": "没.*需求,没.*打算,没.*想法,(没|不).*需要,不.*感兴趣,没.*兴趣,(没|不).*考虑,暂时,目前,用不着,用不到,不了,(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见),打错,没兴趣,搞错,不感兴趣,没.*需要,不需要,不愿意,已经.*(有|过),我说我不,不做,不用,不想,算了,没有,再见,挂了,加过,没时间,不必,没必要,算了吧,打错了,暂时不,打错电话,没.*接触,不了解,不知道,^((?!听不清楚|说不清楚).)*不清楚,不是,不是本人,不是我,(别人|人家).*办的,没有欠钱,不记得,没用过,没(借|欠)过,(时间|时候).*(借欠)(过|的|得),没.*(借|欠|消费)过,没有用过,我没借,我没有借,我不欠,(不|没).*(认识|下过).*(软件|平台|A|a),不认识,认不到",
                  "decisionType": 0,
                  "acceptBreak": 0,
                  "afterBreakType": 0,
                  "action": 1,
                  "knowledgeBaseId": null,
                  "path": "956.9615000000001 350.5684",
                  "nodeType": 1,
                  "intentionDef": "{}",
                  "labelInfoIds": null,
                  "labelInfoItem": [],
                  "actionParam": "{}",
                  "smsTemplateId": -1,
                  "answerKeywordDef": null,
                  "useEavesdrop": 0,
                  "eavesdropParam": "",
                  "attachmentSendFlag": 0,
                  "attachment": null,
                  "ttsType": 2,
                  "transferSeatGroupId": null,
                  "transferAction": null,
                  "transferTelephone": null,
                  "transferTelephoneEditable": false,
                  "ivrParam": null,
                  "childrenList": []
                }
              ]
            }
          ]
        }
      ]
    },
    "decisionItemBOList": [
      {
        "decisionId": 7615464,
        "sceneDefId": 73094,
        "parentId": 7615842,
        "sceneNodeId": 529526,
        "name": "普通话术",
        "answerIds": [
          "默认"
        ],
        "childrenAnswerIds": [
          "肯定",
          "否定",
          "默认",
          "特殊"
        ],
        "refererId": null,
        "knowledge": "我这边是百应平台，请问您是${客户名称}吗？",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": 1,
        "keyword": "",
        "decisionType": 0,
        "acceptBreak": 1,
        "afterBreakType": 1,
        "action": 2,
        "knowledgeBaseId": null,
        "path": "557.9780000000001 -45.68159999999989",
        "nodeType": 0,
        "intentionDef": "{\"客户意向等级\":\"C级(明确拒绝)\"}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": null,
        "smsTemplateId": -1,
        "answerKeywordDef": "{\"肯定\":[\"有需要\",\"说下\",\"讲下\",\"你讲\",\"行啊\",\"了解下\",\"说吧\",\"对的\",\"对啊\",\"确实是\",\"是的\",\"当然\",\"肯定\",\"能去\",\"能啊\",\"行行\",\"接触过\",\"了解过\",\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\",\"是\",\"^[^不]*是的\",\"怎么\",\"^[^在]*哪里\",\"(说|干|做)(啥|什么|嘛)\",\"你说\",\"我是\",\"是啊\",\"嗯对\",\"嗯是\",\"^[^不]*(是我本人|是本人)\"],\"拒绝\":[\"暂时\",\"目前\",\"用不着\",\"用不到\",\"不了\",\"(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见)\",\"打错\",\"没兴趣\",\"搞错\",\"不感兴趣\",\"没.*需要\",\"不需要\",\"不愿意\",\"不考虑\",\"已经.*(有|过)\",\"我说我没\",\"我说我不\",\"不做\",\"不缺钱\",\"我有钱\",\"不用\",\"不想\",\"算了\",\"没有\",\"再见\",\"挂了\",\"加过\",\"没时间\",\"不必\",\"没必要\",\"算了吧\",\"打错了\",\"暂时不\",\"打错电话\",\"没.*接触\",\"不了解\",\"不知道\",\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\",\"不是\",\"不是本人\",\"不是我\",\"(别人|人家).*办的\",\"没有欠钱\",\"不记得\",\"没用过\",\"没(借|欠)过\",\"(时间|时候).*(借欠)(过|的|得)\",\"没.*(借|欠|消费)过\",\"没有用过\",\"打错了\",\"我没借\",\"我没有借\",\"我不欠\",\"(不|没).*(认识|下过).*(软件|平台|A|a)\",\"不认识\",\"认不到\"],\"特殊\":[\"干嘛\",\"做啥\",\"干啥\",\"哪的\",\"哪块\",\"没听清\",\"再说一遍\",\"有事\",\"哪个\",\"你说撒\",\"没信号\",\"听.*清\",\"你.*谁\"]}",
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": null,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7615465,
        "sceneDefId": 73094,
        "parentId": 7615464,
        "sceneNodeId": 529526,
        "name": "跳转话术",
        "answerIds": [
          "肯定"
        ],
        "childrenAnswerIds": [],
        "refererId": null,
        "knowledge": "",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "有需要,说下,讲下,你讲,行啊,了解下,说吧,对的,对啊,确实是,是的,当然,肯定,能去,能啊,行行,接触过,了解过,^((?!没有需要).)*有需要,^[^没]*需求,^[^(不|没)]*兴趣,是,^[^不]*是的,怎么,^[^在]*哪里,(说|干|做)(啥|什么|嘛),你说,我是,是啊,嗯对,嗯是,^[^不]*(是我本人|是本人)",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 0,
        "action": 3,
        "knowledgeBaseId": null,
        "path": "269.98900000000003 130.94365000000005",
        "nodeType": 1,
        "intentionDef": "{}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": "{}",
        "smsTemplateId": null,
        "answerKeywordDef": null,
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": null,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7615466,
        "sceneDefId": 73094,
        "parentId": 7615464,
        "sceneNodeId": 529526,
        "name": "普通话术",
        "answerIds": [
          "默认",
          "特殊"
        ],
        "childrenAnswerIds": [
          "肯定",
          "拒绝",
          "否定",
          "默认"
        ],
        "refererId": null,
        "knowledge": "您好，是这样的，我这边是百应平台，请问您是${客户名称}吗？",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "干嘛,做啥,干啥,哪的,哪块,没听清,再说一遍,有事,哪个,你说撒,没信号,听.*清,你.*谁",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 1,
        "action": 2,
        "knowledgeBaseId": null,
        "path": "557.9780000000001 156.39840000000004",
        "nodeType": 0,
        "intentionDef": "{}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": null,
        "smsTemplateId": -1,
        "answerKeywordDef": "{\"肯定\":[\"有需要\",\"说下\",\"讲下\",\"你讲\",\"行啊\",\"了解下\",\"说吧\",\"对的\",\"对啊\",\"确实是\",\"是的\",\"当然\",\"肯定\",\"能去\",\"能啊\",\"行行\",\"接触过\",\"了解过\",\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\",\"^[^不]*是的\",\"怎么\",\"^[^在]*哪里\",\"(说|干|做)(啥|什么|嘛)\",\"你说\",\"我是\",\"是啊\",\"嗯对\",\"嗯是\"],\"拒绝\":[\"暂时\",\"目前\",\"用不着\",\"用不到\",\"不了\",\"(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见)\",\"打错\",\"没兴趣\",\"搞错\",\"不感兴趣\",\"没.*需要\",\"不需要\",\"不愿意\",\"已经.*(有|过)\",\"我说我不\",\"不做\",\"不用\",\"不想\",\"算了\",\"没有\",\"再见\",\"挂了\",\"加过\",\"没时间\",\"不必\",\"没必要\",\"算了吧\",\"打错了\",\"暂时不\",\"打错电话\",\"没.*接触\",\"不了解\",\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\",\"不是\",\"不是本人\",\"不是我\",\"(别人|人家).*办的\",\"没有欠钱\",\"不记得\",\"没用过\",\"没(借|欠)过\",\"(时间|时候).*(借欠)(过|的|得)\",\"没.*(借|欠|消费)过\",\"没有用过\",\"打错了\",\"我没借\",\"我没有借\",\"我不欠\",\"(不|没).*(认识|下过).*(软件|平台|A|a)\",\"不认识\",\"认不到\"]}",
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": null,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7615467,
        "sceneDefId": 73094,
        "parentId": 7615466,
        "sceneNodeId": 529526,
        "name": "跳转话术",
        "answerIds": [
          "肯定",
          "默认"
        ],
        "childrenAnswerIds": [],
        "refererId": null,
        "knowledge": "",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "有需要,说下,讲下,你讲,行啊,了解下,说吧,对的,对啊,确实是,是的,当然,肯定,能去,能啊,行行,接触过,了解过,^((?!没有需要).)*有需要,^[^没]*需求,^[^(不|没)]*兴趣,^[^不]*是的,怎么,^[^在]*哪里,(说|干|做)(啥|什么|嘛),你说,我是,是啊,嗯对,嗯是",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 0,
        "action": 3,
        "knowledgeBaseId": null,
        "path": "206.99450000000002 317.06864999999993",
        "nodeType": 1,
        "intentionDef": "{}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": "{}",
        "smsTemplateId": null,
        "answerKeywordDef": null,
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": null,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7615468,
        "sceneDefId": 73094,
        "parentId": 7615466,
        "sceneNodeId": 529526,
        "name": "跳转话术",
        "answerIds": [
          "拒绝",
          "否定"
        ],
        "childrenAnswerIds": [],
        "refererId": null,
        "knowledge": "不好意思，打扰了，${客户名称}在我们百应平台的借款即将到期，请您尽快通知他还款，谢谢，这边先不打扰了，再见！",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "暂时,目前,用不着,用不到,不了,(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见),打错,没兴趣,搞错,不感兴趣,没.*需要,不需要,不愿意,已经.*(有|过),我说我不,不做,不用,不想,算了,没有,再见,挂了,加过,没时间,不必,没必要,算了吧,打错了,暂时不,打错电话,没.*接触,不了解,没.*需求,没.*打算,没.*想法,(没|不).*需要,不.*感兴趣,没.*兴趣,(没|不).*考虑,不知道,^((?!听不清楚|说不清楚).)*不清楚,不是,不是本人,不是我,(别人|人家).*办的,没有欠钱,不记得,没用过,没(借|欠)过,(时间|时候).*(借欠)(过|的|得),没.*(借|欠|消费)过,没有用过,我没借,我没有借,我不欠,(不|没).*(认识|下过).*(软件|平台|A|a),不认识,认不到",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 0,
        "action": 1,
        "knowledgeBaseId": null,
        "path": "448.98350000000005 353.5684",
        "nodeType": 1,
        "intentionDef": "{}",
        "labelInfoIds": "[12091]",
        "labelInfoItem": [
          {
            "name": "不是本人",
            "id": 12091
          }
        ],
        "actionParam": "{}",
        "smsTemplateId": -1,
        "answerKeywordDef": null,
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": null,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7615842,
        "sceneDefId": 73094,
        "parentId": -1,
        "sceneNodeId": 529526,
        "name": "普通话术",
        "answerIds": [],
        "childrenAnswerIds": [
          "默认"
        ],
        "refererId": null,
        "knowledge": "喂，您好",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": 1,
        "keyword": null,
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 1,
        "action": 2,
        "knowledgeBaseId": null,
        "path": "557.9780000000001 -247.76159999999996",
        "nodeType": 0,
        "intentionDef": "{\"客户意向等级\":\"C级(明确拒绝)\"}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": null,
        "smsTemplateId": -1,
        "answerKeywordDef": "{\"肯定\":[\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\"],\"拒绝\":[\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\"]}",
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": 0,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7617921,
        "sceneDefId": 73094,
        "parentId": 7615464,
        "sceneNodeId": 529526,
        "name": "普通话术",
        "answerIds": [
          "否定"
        ],
        "childrenAnswerIds": [
          "肯定",
          "拒绝",
          "否定",
          "默认"
        ],
        "refererId": null,
        "knowledge": "不好意思，我这边需要再次确认一下您是不是${客户名称}?",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "不知道,^((?!听不清楚|说不清楚).)*不清楚,不了解,不是,不是本人,不是我,(别人|人家).*办的,没有欠钱,不记得,没用过,没(借|欠)过,(时间|时候).*(借欠)(过|的|得),没.*(借|欠|消费)过,没有用过,打错了,我没借,我没有借,我不欠,(不|没).*(认识|下过).*(软件|平台|A|a),不认识,认不到",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 1,
        "action": 2,
        "knowledgeBaseId": null,
        "path": "845.9670000000001 156.39840000000004",
        "nodeType": 0,
        "intentionDef": "{\"客户意向等级\":\"C级(明确拒绝)\"}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": null,
        "smsTemplateId": -1,
        "answerKeywordDef": "{\"肯定\":[\"^((?!没有需要).)*有需要\",\"^[^没]*需求\",\"^[^(不|没)]*兴趣\",\"^[^不]*是的\",\"怎么\",\"^[^在]*哪里\",\"(说|干|做)(啥|什么|嘛)\",\"你说\",\"我是\",\"是啊\",\"嗯对\",\"嗯是\"],\"拒绝\":[\"没.*需求\",\"没.*打算\",\"没.*想法\",\"(没|不).*需要\",\"不.*感兴趣\",\"没.*兴趣\",\"(没|不).*考虑\",\"暂时\",\"目前\",\"用不着\",\"用不到\",\"不了\",\"(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见)\",\"打错\",\"没兴趣\",\"搞错\",\"不感兴趣\",\"没.*需要\",\"不需要\",\"不愿意\",\"已经.*(有|过)\",\"我说我不\",\"不做\",\"不用\",\"不想\",\"算了\",\"没有\",\"再见\",\"挂了\",\"加过\",\"没时间\",\"不必\",\"没必要\",\"算了吧\",\"打错了\",\"暂时不\",\"打错电话\",\"没.*接触\",\"不了解\"],\"否定\":[\"不知道\",\"^((?!听不清楚|说不清楚).)*不清楚\",\"不了解\",\"不是\",\"不是本人\",\"不是我\",\"(别人|人家).*办的\",\"没有欠钱\",\"不记得\",\"没用过\",\"没(借|欠)过\",\"(时间|时候).*(借欠)(过|的|得)\",\"没.*(借|欠|消费)过\",\"没有用过\",\"打错了\",\"我没借\",\"我没有借\",\"我不欠\",\"(不|没).*(认识|下过).*(软件|平台|A|a)\",\"不认识\",\"认不到\"]}",
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": 0,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7617922,
        "sceneDefId": 73094,
        "parentId": 7617921,
        "sceneNodeId": 529526,
        "name": "跳转话术",
        "answerIds": [
          "肯定",
          "默认"
        ],
        "childrenAnswerIds": [],
        "refererId": null,
        "knowledge": "",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "^((?!没有需要).)*有需要,^[^没]*需求,^[^(不|没)]*兴趣,^[^不]*是的,怎么,^[^在]*哪里,(说|干|做)(啥|什么|嘛),你说,我是,是啊,嗯对,嗯是",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 0,
        "action": 3,
        "knowledgeBaseId": null,
        "path": "701.9725000000001 345.06864999999993",
        "nodeType": 1,
        "intentionDef": "{}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": "{}",
        "smsTemplateId": -1,
        "answerKeywordDef": null,
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": 0,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      },
      {
        "decisionId": 7617923,
        "sceneDefId": 73094,
        "parentId": 7617921,
        "sceneNodeId": 529526,
        "name": "跳转话术",
        "answerIds": [
          "拒绝",
          "否定"
        ],
        "childrenAnswerIds": [],
        "refererId": null,
        "knowledge": "不好意思，打扰了，${客户名称}在我们百应平台的借款即将到期，请您尽快通知他还款，谢谢，这边先不打扰了，再见！",
        "knowledgeOssUrl": null,
        "knowledgeOssFullUrl": null,
        "index": null,
        "keyword": "没.*需求,没.*打算,没.*想法,(没|不).*需要,不.*感兴趣,没.*兴趣,(没|不).*考虑,暂时,目前,用不着,用不到,不了,(唉|哎|啊|哦|嗯|谢谢).*(不需要|不用|不考虑|谢谢|拜拜|挂了|再见),打错,没兴趣,搞错,不感兴趣,没.*需要,不需要,不愿意,已经.*(有|过),我说我不,不做,不用,不想,算了,没有,再见,挂了,加过,没时间,不必,没必要,算了吧,打错了,暂时不,打错电话,没.*接触,不了解,不知道,^((?!听不清楚|说不清楚).)*不清楚,不是,不是本人,不是我,(别人|人家).*办的,没有欠钱,不记得,没用过,没(借|欠)过,(时间|时候).*(借欠)(过|的|得),没.*(借|欠|消费)过,没有用过,我没借,我没有借,我不欠,(不|没).*(认识|下过).*(软件|平台|A|a),不认识,认不到",
        "decisionType": 0,
        "acceptBreak": 0,
        "afterBreakType": 0,
        "action": 1,
        "knowledgeBaseId": null,
        "path": "956.9615000000001 350.5684",
        "nodeType": 1,
        "intentionDef": "{}",
        "labelInfoIds": null,
        "labelInfoItem": [],
        "actionParam": "{}",
        "smsTemplateId": -1,
        "answerKeywordDef": null,
        "useEavesdrop": 0,
        "eavesdropParam": "",
        "attachmentSendFlag": 0,
        "attachment": null,
        "ttsType": 2,
        "transferSeatGroupId": null,
        "transferAction": null,
        "transferTelephone": null,
        "transferTelephoneEditable": false,
        "ivrParam": null
      }
    ]
  },
  "resultMsg": "获取成功",
  "errorStackTrace": null,
  "requestId": "3cbaf7fb80c041b9"
}